preprocessed_dir: 'preprocessed'
#label_list:  ['positive', 'negative', 'neutral']
emb_dim: 300
output_channels: 100
speaker_emb_dims: 300
project_dims: 300
max_length: 1000
#batch_size: 2
epoch_size: 30
train_mode: random
filters: [3,4,5]
dropout: 0.5
shuffle: Fasle
learning_rate: 2e-4
bert_lr: 2e-4
patience: 100
max_grad_norm: 1.0
warmup_proportion: 0.1
gradient_accumulation_steps: 1
adam_epsilon: 1e-8
warmup_steps: 0
weight_decay: 0.01
#seed: 42 19 97
seed: 97
